# Generated by Django 2.2.5 on 2019-09-17 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'MyTweet', 'verbose_name_plural': 'tweets'},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text',
        ),
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, max_length=163, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
