# Generated by Django 2.2.5 on 2019-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190926_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, error_messages={'max_length': 'you can write at most 10 characters'}, max_length=10, null=True),
        ),
    ]
