# Generated by Django 2.2.5 on 2019-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20190926_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, error_messages={'max_length': 'you can write at most 10 characters'}, max_length=140, null=True),
        ),
    ]
