# Generated by Django 2.2.5 on 2019-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
