# Generated by Django 2.2.5 on 2019-10-16 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0010_tweet_retweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
