# Generated by Django 2.2.5 on 2019-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Reply',
            field=models.BooleanField(default=False, verbose_name='is_a_reply?'),
        ),
    ]
