# Generated by Django 2.2.5 on 2019-11-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_tweet_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted',
        ),
    ]
