# Generated by Django 2.2.5 on 2019-10-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tags',
            new_name='tag',
        ),
    ]
