# Generated by Django 2.2.5 on 2019-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtag', '0002_auto_20191014_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
