# Generated by Django 2.2.5 on 2019-11-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtag', '0003_hashtag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='count',
        ),
    ]
