# Generated by Django 2.2.5 on 2019-11-11 14:16

from django.db import migrations, models
from ..models import hashtag

def migrate_data_forward(apps, schema_editor):
    for instance in hashtag.objects.all():
        print("increment count for {}".format(instance))
        instance.count=instance.count+1
        instance.save() # Will trigger slug update

class Migration(migrations.Migration):

    dependencies = [
        ('Hashtag', '0004_remove_hashtag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),migrations.RunPython(
            migrate_data_forward
        ),
    ]
