# Generated by Django 2.2.5 on 2019-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtag', '0005_hashtag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
