# Generated by Django 2.2.5 on 2019-09-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid UserName', message='The username must be Aplanumeric or contain any of the following @ . - +', regex='^[a-zA-Z0-9.@+-]*$')], verbose_name='UserName'),
        ),
    ]
