# Generated by Django 2.2.5 on 2019-10-02 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191001_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This Email Address is already registered '}, max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid UserName', message='The username must be Aplanumeric or contain any of the following @ . - +', regex='^[a-zA-Z0-9.@+-]*$')], verbose_name='UserName'),
        ),
    ]
