# Generated by Django 2.2.5 on 2019-10-05 00:15

import autoslug.fields
import django.core.validators
from django.db import migrations, models
from django.contrib.auth import  get_user_model
User = get_user_model()

def migrate_data_forward(apps, schema_editor):
    for instance in User.objects.all():
        print("Generating slug for {}".format(instance))
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191002_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=120, null=True, populate_from='username', unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This Username is already registered '}, max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid UserName', message='The username must be Aplanumeric or contain any of the following @ . - +', regex='^[a-zA-Z0-9.@+-]*$')], verbose_name='UserName'),
        ),migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
