# Generated by Django 2.2.5 on 2019-10-05 21:34

import autoslug.fields
from django.db import migrations
from django.contrib.auth import  get_user_model
User = get_user_model()

def migrate_data_forward(apps, schema_editor):
    for instance in User.objects.all():
        print("Generating slug for {}".format(instance))
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_myuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=120, null=True, populate_from='username', unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward
        )
    ]
