# Generated by Django 2.2.5 on 2019-10-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_myuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
