# Generated by Django 2.2.5 on 2019-10-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_myuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
