# Generated by Django 2.2.5 on 2019-10-08 23:05

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191009_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='kuwait', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
