# Generated by Django 2.2.5 on 2019-10-09 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191009_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
