# Generated by Django 2.2.5 on 2019-11-13 11:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20191113_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='mine/empty_pic.jpeg', null=True, upload_to=accounts.models.content_file_name, verbose_name='Profile Picture'),
        ),
    ]
